# Generated by Django 3.1.7 on 2021-03-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
