# Generated by Django 3.1.7 on 2021-03-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20210310_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Liked by')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Post in the blog')),
            ],
        ),
    ]
