# Generated by Django 3.1.7 on 2021-03-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20210313_1401'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postslikes',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Liked by'),
        ),
        migrations.AddField(
            model_name='postslikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.posts', verbose_name='Post in the blog'),
        ),
    ]
